minimumReleaseAge: 4320
minimumReleaseAgeStrict: false
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
trustLockfile: false
allowBuilds:
  esbuild: true
  unrs-resolver: true
